### ISSUE TITLE
Work with Always Centered module?

### ISSUE THREAD

**Issue by dangerdaren** [ironmonk88/monks-common-display#1]
I've been looking for a module that does exactly this--hides everything but the chat window for streaming purposes. But the other module I use is Always Centered, which makes it so the screen dynamically adjusts to always show all the PCs at once. Unfortunately your module keeps Always Centered from working.

Is there a way that you could add an option give camera control over to Always Centered?

**Comment by ironmonk88** [comment]
If you turn off Mirror Movement it should stop Common Display from taking control of the screen.

**Comment by ironmonk88** [comment]
Closing this as I believe there is a setting that will work with Always Centered.
Feel free to re-open if this is not the case.
