### ISSUE TITLE
BUG: Combat Screen always displays... sometimes.

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-common-display#15]
There seems to be an issue where a tiny window is permanently displayed with the current player's turn listed. I only have "Mirror Movement" and "Show Chat Log" checked in settings. "Show Combat" is unchecked.

I seem to be able to fix the problem by clicking the "Change Settings" button, and unchecking "Display", then closing the Combat Tracker window manually, then going back into "Change Settings" and re-checking Display. But this is kind of a pain to have to do every time I refresh the window.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
