### ISSUE TITLE
REQUEST: Make compatible with "Image Hover" module.

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-common-display#2]
Would it be possible to make this module compatible with Image Hover? I like to use this module to show character portraits, but your module (which is nearly perfect for my purposes) overrides this module.

**Comment by ironmonk88** [comment]
You would like Image Hover to work on the screen using the Common Display?

**Comment by GambetTV** [comment]
Correct!

**Comment by ironmonk88** [comment]
Image Hover should be working now.
Released with version 1.0.1.
