### ISSUE TITLE
Restrict the view of token in combat

### ISSUE THREAD

**Issue by ironmonk88** [ironmonk88/monks-common-display#21]
During combat restrict the view to the active token if owned by players.

**Comment by bugbeersandflagons** [comment]
I just came here to suggest this feature!  Having the display "user" select the active token in combat would be nice.  I have started using this module in place of "Hotseat Observer", which no longer works in v9.  That module had a dedicated "player", with ownership of all player tokens - during combat if the active token belonged to the observer, it would select it and display it's line of sight.

I'm not sure if something similar is possible with your implementation - but it would be great to have something like that - the look of your module with the initiative tracker and combat chat log is great - thank you!

**Comment by vexofp** [comment]
I achieve this currently my combining this module with Next Up. Among its other features, Next Up automatically selects the corresponding token at the start of the turn. With Common Display's Mirror Token Selection active, this has the effect of limiting the common display's sight to the active character on their turn (and showing the union of all character's sight on NPC turns). I can still override it if necessary by changing the selection.

Works great so far. 😄

**Comment by Mist-Hunter** [comment]
FYI, [Monk's Little Details ](https://foundryvtt.com/packages/monks-little-details)also handles this token change in combat task. The two work well together.

**Comment by ironmonk88** [comment]
Latest version has the option available.
