### ISSUE TITLE
Show to Players not working

### ISSUE THREAD

**Issue by bugbeersandflagons** [ironmonk88/monks-common-display#22]
I have 2 sessions open - one as DM and one as the "Display" character.  Screen mirroring and token selection mirroring are on.  While in display mode, if I click "Show to Players" on a journal entry, this does not display to the display user.  As soon as display mode is disabled and the UI reappears, the display player has the artwork/journal entry shown.  Putting display mode back on hides it again.

Is this intended behaviour, or a bug?

**Comment by vexofp** [comment]
Working fine for me with 1.0.11, FVTT v9-242, and 5e 1.5.7; journals appear on the common display when "Show to Players" is clicked (both text and image), and are removed when "Clear Journal Entries" is clicked.

**Comment by ironmonk88** [comment]
Can you check with the latest v10 version to see if this is still an issue?

**Comment by ironmonk88** [comment]
Closing this as there's been no response and a newer version is out that changes a lot of that functionality.
