### ISSUE TITLE
REQUEST: Add shortcuts for cleaning text and images

### ISSUE THREAD

**Issue by davelamorte** [ironmonk88/monks-common-display#24]
Hello, thank you so much for this great module!

I find myself having to go often to the controls on the left, to clean up images and texts that I've shared to players.
Can you add a keyboard shortcut for each?
There are already 2 shortcuts for mirror screen and mirror token selection, but I think cleaning up is just as important, if not more!

Thank you.

**Comment by ironmonk88** [comment]
Added to the latest release.
