### ISSUE TITLE
What does this module actually do?

### ISSUE THREAD

**Issue by geoidesic** [ironmonk88/monks-common-display#25]
The description in the README seems to make the assumption that one already knows what this module is for.
I read the README and was left clueless.
I installed it and clicked all the buttons it provides – nothing happened.
I have no idea what it's for.

Could you please update the README file with a description of what the intended use for this component is... and how to use it?

For example the README says: `Set up a display without all the ui so that it can be displayed on an alternate screen.`

1. What do you mean by "setup a display"? And how would one "setup a display"?
1. What do you mean by "alternate screen"? And why would you want to have foundry "displayed on an alternate screen"? And how would you then "display it on an alternate screen"?
1. What is the user experience problem that this solves?
1. What does this mean – "select which player is to be used as your display player"? What is a "display player"?

**Comment by ShiftyRat** [comment]
This module is for when you're using Foundry to help support an in-person game session (i.e., you're all crowded around a TV or similar display).

This YouTube video goes over the use case quite nicely:
https://youtu.be/JOBL7NPk8Lk?t=55

**Comment by ironmonk88** [comment]
Updated the Readme.
