### ISSUE TITLE
Party View

### ISSUE THREAD

**Issue by hensio10** [ironmonk88/monks-common-display#26]
This module is fantastic but I would like to request that an ability to select a center party view be enabled.   That way if you play in person with the full party on the screen, the view would zoom out to show where every player character token is on the map automatically, keeping the full party centered.   The GM could set up the player characters tokens to be owned by one profile and that profile could be used to show the full view of the party on a TV in front of the live group.   They could then use the other features of this module as needed in their game.   Thanks!

**Comment by ironmonk88** [comment]
Added to the latest release.
