### ISSUE TITLE
[BUG] Cannot see video/audio camera streams

### ISSUE THREAD

**Issue by davelamorte** [ironmonk88/monks-common-display#27]
**Describe the bug**
The common display player's view, does not show the video/audio of the players/GM.
"Show camera views" setting changes nothing.

**To Reproduce**
Nothing major, simply use a clean world with the module active, set it up, and when Common display is activated on a player, all cameras are hidden.

**Expected behavior**
By ticking the option in the settings it should show cameras.

**Please complete as much of the following information as possible:**
 - Browser: Edge, Chrome, OBS internal browser
 - Foundry Version V10.288
 - System D&D5e 2.0.3
 - Module version 10.1

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
