### ISSUE TITLE
[BUG] Screen mirroring crashes with JS error

### ISSUE THREAD

**Issue by YugoNumachi** [ironmonk88/monks-common-display#30]
**Describe the bug**
When trying to activate the screen mirroring, the party browser displays a JS error (reading animate property from undefined).
This occurs even after clearing both browsers caches, and with all other modules disabled. DM is running on Chrome, party is running on Edge, both on the same machine. Version 1.0.14 had no problem

![image](https://user-images.githubusercontent.com/83497401/201110718-3f612cdc-6ddf-4de6-a1df-7df1a0c47521.png)

**To Reproduce**
1. Click on the Screen Mirroring button
2. Go to the Dev Tools on the party browser
3. See the JS error

**Expected behavior**
Mirroring should activate like it used to do in previous versions.

**Screenshots**
See above

**Please complete as much of the following information as possible:**
 - Browser Chrome 107 for DM, Edge 107 for party
 - Foundry Version V10.288
 - System [e.g. D&D5e, Pathfinder 2e]: dnd5e
 - Module version 10.1
 - Are there any errors in the console [e.g. press F12 and look for red text] yes, see screenshot
 - Have you tried using `Find the Culprit` to make sure it isn't a module interaction. all other modules are disabled

**Additional context**
N/A

**Comment by YugoNumachi** [comment]
Here is the output of the onMessage received just before the error:

![image](https://user-images.githubusercontent.com/83497401/201118206-51bc73cf-75c0-49f4-ac63-a2b2308aa249.png)

**Comment by YugoNumachi** [comment]
And I just discovered the right click... I completely missed that from the readme...
Not really obvious, and I still don't really understand what those options do, but... at least it works now...

Sorry for the inconvenience...

**Comment by SirMotte** [comment]
> And I just discovered the right click... I completely missed that from the readme... Not really obvious, and I still don't really understand what those options do, but... at least it works now...
> 
> Sorry for the inconvenience...

For anyone wondering what Yugo is talking about:

If you right click on the Screen and Focus Icon, you can set who the the camera should follow. This fixes the issue for the GM view at least.

![grafik](https://user-images.githubusercontent.com/82598692/206137876-dead5c9b-03aa-402f-a3ec-d0c4d4173ae4.png)
