### ISSUE TITLE
[BUG] Critical error with foundry vtt v10

### ISSUE THREAD

**Issue by Benethor92** [ironmonk88/monks-common-display#31]
I get a critical error as soon as i update to foundry v10:

![grafik](https://user-images.githubusercontent.com/111077874/202721936-9b59f4ed-df89-429e-b37d-4555eab162f9.png)

Got it three months ago in the testing release as well as with the stable release right now. Works fine when i downgrade back to v9.

**Comment by ironmonk88** [comment]
Due to v10 doing weird things, you'll need to re-install the module.  That should clear the error.

**Comment by ironmonk88** [comment]
Closing this as there's a work around and it's kind of a v10 issue.
