### ISSUE TITLE
BUG: Common Display Bar reappears randomly for no reason

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-common-display#33]
Using the most current version of Foundry and your module. If I open up the Common Display Bar, and then close it, it'll just randomly open again. I just saw it happen when I'm not even touching Foundry. I think it might be happening when a player moves or rotates their token, but there's no focus on them.

**Comment by utterlyeclipsed** [comment]
+1 I'm also experiencing this issue. It seems to happen whenever a token is interacted with.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
