### ISSUE TITLE
[BUG] Combat Tracker just shows up sometimes even when it's turned off

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-common-display#34]
The combat tracker shows up if you F5 refresh, and there's literally no way to get rid of it, even by going into the settings, turning on the combat tracker and turning it off again. Nothing seems to work.

**Comment by GambetTV** [comment]
I did a bit more testing, it seems to occur if at any point the Common Display user joins the game or refreshes the game in a scene where combat is already occurring. When this happens, there's no way to fix it except to end combat and reinitialize combat, which obviously isn't feasible in the middle of a big fight.

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.

**Comment by ttrpgfroth** [comment]
This is not fixed in 13.01

The fix is to change [this line](https://github.com/ironmonk108/monks-common-display/blob/9a68919ae2364edfd4d6678aa0ab3d684e40d227/monks-common-display.js#L250) to:
`if (display && setting("show-combat") && game.combats.active) {`
