### ISSUE TITLE
[BUG] Styling issue with the Unofficial Call of Cthulhu System in v10

### ISSUE THREAD

**Issue by utterlyeclipsed** [ironmonk88/monks-common-display#36]
After updating to Foundry v10, there's a styling issue in the CoC system where the screen/focus toolbar is stretched across the whole screen, but it works fine in the D&D 5e system. This continues after all other modules have been turned off, so it seems something between the system and the module is bugging out.

![image](https://user-images.githubusercontent.com/119891342/205725243-ffde8310-4777-488a-af5c-d8008e4e9828.png)

**Comment by ironmonk88** [comment]
Should be fixed in the latest release.
