### ISSUE TITLE
Show 'Smalltime'

### ISSUE THREAD

**Issue by orangebutblue** [ironmonk88/monks-common-display#38]
![st](https://user-images.githubusercontent.com/4688096/214247952-adc709b5-c2ae-41a9-a391-c3fa9d37738f.png)

It should be possible to intentionally show certain elements or exclude them from being hidden when the common display is activated.

One module I personally use is '[Smalltime](https://github.com/unsoluble/smalltime)' which shows the current time of day. I want the players to be able to see that

**Comment by King-Wedgie** [comment]
Tagging in to request including [Grid Labels](https://github.com/illandril/FoundryVTT-grid-labels) for this enhancement, as well

**Comment by BallisticGE0RGE** [comment]
I'd also like to ask for Boss Bar to appear when UI is hidden as well, as that normally works on the Display Mode mod.

**Comment by ironmonk88** [comment]
Added smalltime in the latest release.
