### ISSUE TITLE
REQUEST: Keybind for Mirror Screen Toggle

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-common-display#4]
Could you include a simple keybind, either in the module itself, or within Library: DF Hotkeys to allow us to toggle Mirror Screen on and off, instead of only being able to do it with a mouse click? Appreciate it! Just looking to improve my workflow with this amazing mod!

**Comment by ironmonk88** [comment]
Shouldn't be an issue.
I was going to use the M key... but I swear something else uses that.

**Comment by GambetTV** [comment]
Would it be possible to let it be user-configurable? That way you don't have to worry about it, and people can base it on their own needs. Or plug it into Library: DF Hotkeys! Appreciate it!

**Comment by ironmonk88** [comment]
Oh 100% going with DF Hotkeys.
Just makes life easier.

**Comment by ironmonk88** [comment]
M key has been added using HotKeys.
Released with Version 1.0.1
