### ISSUE TITLE
[Feature Request] Option to set party view minimum zoom level

### ISSUE THREAD

**Issue by King-Wedgie** [ironmonk88/monks-common-display#43]
I stream the Common Display to mobile users on Discord, and the default zoom level for all the player tokens grouped together is a little too far out for comfort during cramped encounters:
![image](https://user-images.githubusercontent.com/73143074/233546635-f54f26a6-0c81-49ac-9ee7-4a7beab62285.png)

Something like this would be preferred:
![image](https://user-images.githubusercontent.com/73143074/233546670-5c649112-bcab-4374-9c6e-fe4171bfa728.png)

An option to adjust the default/minimum zoom would be appreciated. The current work-around is to just manually adjust every time.

**Comment by King-Wedgie** [comment]
Had a thought, and maybe this should be a separate request, but I was thinking that a "Combat/Encounter" view would be helpful for the above issue; basically a similar function to Party view, except that it balances between all visible tokens in the encounter tracker.

**Comment by ironmonk88** [comment]
Added to the latest release.
