### ISSUE TITLE
Way to select a group of tokens for the display not just one.

### ISSUE THREAD

**Issue by AxiumDND** [ironmonk88/monks-common-display#44]
One of the view options we are missing is when a situation happens with a lot of npcs or enemys it would be nice to be able to select a group of tokens to track not just the party. 

a way to add tokens in a scene so they can be tracked or untracked. Mutliple not just a single token.

**Comment by King-Wedgie** [comment]
Yeah, Stream View has this and it makes streaming combat a lot smoother. It would also fix my issue with #43.

**Comment by ironmonk88** [comment]
Added to the latest release.
