### ISSUE TITLE
Do not hide Carousel Combat Tracker from the Common Display

### ISSUE THREAD

**Issue by Kaallis** [ironmonk88/monks-common-display#46]
**Is your feature request related to a problem? Please describe.**
When using the Common Display, it uses the Combat Tracker of Foundry. It can be disabled. I would like to have https://foundryvtt.com/packages/combat-tracker-dock Carousel Combat Tracker available on the Common Display instead.

**Comment by theripper93** [comment]
Carousel Combat Tracker dev here, the module is appended to the `#ui-top` if this information helps

**Comment by ironmonk88** [comment]
Fixed in the latest release.
