### ISSUE TITLE
Party mode - Player moves East

### ISSUE THREAD

**Issue by CarnivorousM** [ironmonk88/monks-common-display#47]
When the 'Screen' setting is set to 'Party' and a token wanders off to the right side of the map (opening and stretching more map open), that particular token eventually vanishes behind the chat. (I cleared the chat to show the graphic of the token back there)

Perhaps put some sort of buffer/padding on the right side to allow the map to scale while that token is still visible.

![image](https://github.com/ironmonk88/monks-common-display/assets/11615728/e9da5514-c914-47dd-bd7f-9939b2e7c938)

**Comment by CarnivorousM** [comment]
Played with this a bit and the far right token can get lost also if a different token goes too far left.

**Comment by ironmonk88** [comment]
Fixed in the latest release.
