### ISSUE TITLE
[BUG] Error detected message on startup

### ISSUE THREAD

**Issue by Zardya** [ironmonk88/monks-common-display#49]
**Describe the bug**
Error message banner on screen when you launch into a world. Console shows the error and only dependencies loaded for testing.
Tested in multiple worlds and created a new world to verify. The common display still operates as intended with the error present.

**To Reproduce**
1. Error is immediately logged on world startup.

**Screenshots**
https://i.gyazo.com/36cf9c1560e0addb06ef0f0fdb1d1302.png
https://i.gyazo.com/e68510549cf57dce742236898a7aee42.png
https://i.gyazo.com/c77536430f94c233932777a648dca87b.jpg

**Please complete as much of the following information as possible:**
 - Chrome: Version 114.0.5735.134 (Official Build) (64-bit)
 - Foundry Version: v10 Build 291
 - System: D&D5e v2.2.1
 - Module version: Monk's Common Display: v11.01, libWrapper: v1.12.12.1
 - Yes errors are present, linked in the screenshots
 - Only one dependency module libWrapper running.

**Comment by ironmonk88** [comment]
version 11.01 is not intended to be run in Foundry v10, and is only meant for v11.
Not entirely sure how this was installed, since the module details should be limiting it to not be installed unless Foundry has been upgraded to v11.
I'd recommend downgrading to the MCD 10.2
