### ISSUE TITLE
BUG: Chat screen returns every refresh

### ISSUE THREAD

**Issue by GambetTV** [ironmonk88/monks-common-display#5]
Love the new update! Only issue is if the Common Display client refreshes, and upon every first login, the Common Display shows the chat room, and the only way to fix it seems to be for the DM to click on the Change Settings Icon, uncheck Display for that client, save, go back into it, recheck display, save again. That fixes it, until the next refresh.

**Comment by ironmonk88** [comment]
That was a weird bug.
Should be fixed now.  Took a different approach to hiding the chat window.
