### ISSUE TITLE
take in the target

### ISSUE THREAD

**Issue by BoTKaPyC** [ironmonk88/monks-common-display#52]
When I select a token in the target, and remove the target through T, it gives an error.
![Без имени](https://github.com/ironmonk88/monks-common-display/assets/80960291/48e0de58-8678-425d-a41e-5db0596f17e6)
System Pathfinder 2e

**Comment by BoTKaPyC** [comment]
![image](https://github.com/ironmonk88/monks-common-display/assets/80960291/8b41a946-07ce-4cbe-a925-070666af38e3)

**Comment by ironmonk88** [comment]
Added to the latest release.
