### ISSUE TITLE
Monk's Common Display excluding Boss Bar

### ISSUE THREAD

**Issue by HuskyHighlander23** [ironmonk88/monks-common-display#53]
**Is your feature request related to a problem? Please describe.**
Using the module Boss Bar https://foundryvtt.com/packages/bossbar it does not show up with UI is hidden for Monk's Common Display. 

**Describe the solution you'd like**
Please exclude Boss Bar from elements that are hidden with common display. 

**Additional context**
Thank you, I love you.

**Comment by ironmonk88** [comment]
Added BossBar in the latest release.
