### ISSUE TITLE
REQUEST: Make compatible with "Health Estimate 2" module.

### ISSUE THREAD

**Issue by vexofp** [ironmonk88/monks-common-display#6]
The [Health Estimate 2](https://github.com/mclemente/healthEstimate) module adds a token HUD that provides a rough indication of the target's health (as an alternative to a precise health bar). It would be nice for this to be visible on the common display, since this information is intended for the players' benefit. Unfortunately, it is currently hidden along with the rest of the UI.

It looks like Health Estimate applies a [`healthEstimate` class](https://github.com/mclemente/healthEstimate/blob/master/module/logic.js#L37) to its HUD that may be useful for excluding it via CSS.

**Comment by ironmonk88** [comment]
Health Estimate should be visible now.
