### ISSUE TITLE
Foundry 0.8.5 Error

### ISSUE THREAD

**Issue by bklick** [ironmonk88/monks-common-display#7]
Hi!

I hope that you will maintain this mod into the transition to 0.8.x, as it is mission-critical in my home games.

As of right now, it causes all scenes to display nothing but black pixels.

Thank you for all of your hard work! I love your modules

B

**Comment by ironmonk88** [comment]
Huh.  Beat me by a couple of minutes.  :-)
1.0.4 has been released.  Support for 0.8.x

**Comment by bklick** [comment]
Have I mentioned that you, godlike, beam your light into a world of sludge-stained mortals?
